# Generated by Django 5.1.6 on 2025-05-20 11:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('customer', 'Customer'), ('business', 'Business')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('file', models.ImageField(blank=True, null=True, upload_to='profile_pictures/')),
                ('location', models.CharField(blank=True, default='München', max_length=50, null=True)),
                ('tel', models.CharField(blank=True, default='0152435465', max_length=20, null=True)),
                ('description', models.CharField(blank=True, default='Deine Beschreibung', max_length=150, null=True)),
                ('working_hours', models.CharField(blank=True, default='9-17', max_length=20, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
                'ordering': ['-created_at'],
            },
        ),
    ]
