# Generated by Django 5.1.6 on 2025-05-21 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='description',
            field=models.CharField(blank=True, default='Your Description', max_length=150, null=True),
        ),
    ]
