# Generated by Django 5.1.6 on 2025-05-13 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='offer',
            options={'ordering': ['-created_at'], 'verbose_name': 'Offer', 'verbose_name_plural': 'Offers'},
        ),
        migrations.AlterModelOptions(
            name='offerdetail',
            options={'ordering': ['price'], 'verbose_name': 'Offer Detail', 'verbose_name_plural': 'Offer Details'},
        ),
    ]
