CATEGORIES = [
    # Tech / Produkt
    "Webentwicklung",
    "App-Entwicklung",
    "UI/UX Design",
    "Datenanalyse",
    "DevOps & Cloud",
    "QA & Testing",
    "SEO/Content",
    "Automatisierung",
    "E-Commerce & CMS",
    "IT & Netzwerk",
    "Cybersecurity",
    "KI/ML & Data Science",
    "Game Development",
    "Produktmanagement",
    # Kreativ
    "Grafikdesign & Branding",
    "Video & Animation",
    "Audio & Musik",
    "Fotografie & Bildbearbeitung",
    # Business/Marketing
    "Schreiben & Übersetzen",
    "Digital Marketing",
    "Sales & Leadgen",
    "Social Media Management",
    "PR & Kommunikation",
    # Operations
    "Admin & Assistenz",
    "Projektmanagement",
    "Finanzen & Buchhaltung",
    "HR & Recruiting",
    # Spezial
    "Architektur & CAD",
    "E-Learning & Bildung",
    "Rechtsdokumente (allgemein)",
    "Research & Analyse",
]

OFFER_TEMPLATES = {
    "Webentwicklung": [
        (
            "Landingpage in Next.js",
            "SEO-freundliche Landingpage inkl. Deployment & Tracking.",
        ),
        ("Django REST API", "Saubere REST API inkl. Auth, Swagger und Tests."),
        ("React App Refactor", "Refactoring, State-Management und Performance-Tuning."),
    ],
    "App-Entwicklung": [
        ("Flutter MVP", "Cross-platform MVP inkl. State-Management & CI."),
        ("React Native App Setup", "RN App mit Navigation, Auth und OTA Updates."),
        ("Store-Submission", "Vorbereitung & Einreichung in App/Play Store."),
    ],
    "UI/UX Design": [
        ("Design System (Figma)", "Komponentenbasiertes Design-System mit Doku."),
        ("UX-Audit", "Heuristisches Audit + klickbarer Prototyp."),
        ("User Flow & Wireframes", "Low-/Mid-Fi Wireframes inkl. Feedback-Runden."),
    ],
    "Datenanalyse": [
        ("ETL Pipeline", "Daten-Pipeline (Airflow/Pandas) + Reports."),
        ("Dashboard (Plotly/Dash)", "Interaktives Dashboard inkl. Auth & Export."),
        ("SQL-Reporting", "Wiederverwendbare SQL-Views & Kennzahlen."),
    ],
    "DevOps & Cloud": [
        ("Dockerize & CI", "Dockerisierung + CI/CD (GitHub Actions)."),
        ("Kubernetes Basics", "K8s-Deployment (Ingress, HPA) für bestehende App."),
        ("Monitoring Setup", "Prometheus/Grafana inkl. Alerts."),
    ],
    "QA & Testing": [
        ("Test Suite Aufbau", "Pytest/DRF Tests, Coverage und Reporting."),
        ("E2E Setup", "Playwright/Cypress E2E inkl. Seeds und Mocks."),
        ("Load/Stress Test", "k6/JMeter Lasttests mit Auswertung."),
    ],
    "SEO/Content": [
        ("Techn. SEO", "Core Web Vitals, Sitemap, Meta, strukturierte Daten."),
        ("Content Landing", "Keyword-Landingpage inkl. CMS-Hook."),
        ("SEO-Audit", "On-/Off-Page Analyse mit Maßnahmenplan."),
    ],
    "Automatisierung": [
        ("Scripting Bundle", "Automationen (Python) für Workflows."),
        ("RPA Light", "Browser/Desktop-Automationen für wiederkehrende Tasks."),
        ("Zapier/Make Flows", "No-Code Automations inkl. Fehlertoleranz."),
    ],
    "E-Commerce & CMS": [
        ("Shopify Setup", "Theme-Anpassung, Produkte, Zahlungen, Apps."),
        ("WooCommerce Fix", "Bugfixes, Payment/Versand-Integration."),
        ("Headless CMS", "Strapi/Contentful Setup + Frontend-Hook."),
    ],
    "IT & Netzwerk": [
        ("VPN/Firewall Setup", "Sichere Site-to-Site/Remote VPN-Konfiguration."),
        ("Server Härtung", "SSH-Hardening, Fail2ban, Updates, Backup."),
    ],
    "Cybersecurity": [
        ("Sec-Audit Light", "OWASP-Checkliste, Security-Headers, Secrets-Scan."),
        ("Pentest Basic", "Black/Gray-Box Kurztest + Report."),
    ],
    "KI/ML & Data Science": [
        ("Feature Engineering", "Vorbereitung & Feature-Pipelines für ML."),
        ("ML Modell Quickstart", "Baseline-Modelle + Evaluation."),
        ("LLM Integration", "Prompt-Flows, Vektorsuche, Guardrails."),
    ],
    "Game Development": [
        ("Unity Prototype", "Gameplay-Prototype inkl. Input & UI."),
        ("Asset Integration", "Level, Audio, FX in bestehendem Projekt."),
    ],
    "Produktmanagement": [
        ("Produkt Discovery", "Hypothesen, JTBD, Value Proposition Canvas."),
        ("Backlog Setup", "Epics/Stories, Priorisierung, Roadmap Light."),
    ],
    "Grafikdesign & Branding": [
        ("Logo & Mini-CI", "Logo, Farbwelt, Typo + Brand-Sheet."),
        ("Social Assets", "Templates für Posts/Stories/Banner."),
        ("Brand Guidelines", "Kompaktes Styleguide-Dokument."),
    ],
    "Video & Animation": [
        ("Short-Form Edits", "TikTok/Reels/Shorts inkl. Captions."),
        ("Explainer (2D)", "Kurz-Erklärvideo mit Voiceover."),
        ("Motion Graphics", "Intro/Lower Thirds/Transitions Paket."),
    ],
    "Audio & Musik": [
        ("Podcast Schnitt", "Rauschreduzierung, Mastering, Kapitelmarken."),
        ("Jingle/Intro", "Kurzer Marken-Jingle (royalty-free)."),
    ],
    "Fotografie & Bildbearbeitung": [
        ("Retusche Paket", "Skin, Licht, Farblook, Export-Presets."),
        ("Produktfreisteller", "E-Com-ready PNG/JPG, konsistenter Schatten."),
    ],
    "Schreiben & Übersetzen": [
        ("Blog-Artikel", "Strukturierter Fachartikel inkl. Quellen."),
        ("Übersetzung DE↔EN", "Kontextgetreu, leichte Lokalisierung."),
        ("UX-Microcopy", "Buttons, Leermeldungen, Onboarding-Texte."),
    ],
    "Digital Marketing": [
        ("SEA Kampagne", "Google Ads Setup + Tracking + A/B."),
        ("Newsletter Setup", "Template, Automationen, List Hygiene."),
        ("Analytics", "GA4/Matomo Events, Funnels, Dashboards."),
    ],
    "Sales & Leadgen": [
        ("B2B Leadlist", "ICP-basierte Liste inkl. Kontaktdaten."),
        ("Outbound Sequenzen", "E-Mail/LinkedIn Copy + Rhythmus."),
    ],
    "Social Media Management": [
        ("Content-Plan", "30-Tage Plan mit Themen/Visuals."),
        ("Community Mgmt", "Antworten, Moderation, KPI-Report."),
    ],
    "PR & Kommunikation": [
        ("Pressemitteilung", "Struktur, Zitate, Verteiler-Tipps."),
        ("Case Study", "Use-Case Story inkl. Grafiken."),
    ],
    "Admin & Assistenz": [
        ("Research Paket", "Vergleiche, Shortlists, Quellen-Doku."),
        ("Datenpflege", "CRM/Sheets Aufbereitung & Bereinigung."),
    ],
    "Projektmanagement": [
        ("Projekt Kickoff", "Scope, Risiken, Stakeholder-Map."),
        ("Agile Coaching", "Scrum/Kanban Setup + Routinen."),
    ],
    "Finanzen & Buchhaltung": [
        ("Rechnungsworkflow", "Vorlagen, Kategorien, Export."),
        ("Kostenanalyse", "Fix/Variabel, Quick-Savings, Visuals."),
    ],
    "HR & Recruiting": [
        ("Stellenprofil", "Anforderungsprofil, Scorecards."),
        ("Screening Paket", "Vorselektion, Interview-Leitfaden."),
    ],
    "Architektur & CAD": [
        ("Grundriss-Redraw", "Saubere CAD-Dateien aus Skizzen."),
        ("3D Visualisierung", "Schnelle Interior/Exterior-Renders."),
    ],
    "E-Learning & Bildung": [
        ("Kurskonzept", "Lernziele, Module, Quiz-Ideen."),
        ("LMS Setup", "Moodle/Teachable Grundsetup."),
    ],
    "Rechtsdokumente (allgemein)": [
        ("AGB/Privacy Vorlage", "Allg. Muster + Hinweise (keine Rechtsberatung)."),
        ("Vertrags-Template", "Basis-Vorlage zur internen Verwendung."),
    ],
    "Research & Analyse": [
        ("Wettbewerbsanalyse", "Mit Stärken/Schwächen & Positionierung."),
        ("Kunden-Interviews", "Leitfaden, Auswertung, Insights."),
    ],
}

CATEGORY_IMAGE_MAP = {
    "Webentwicklung": "webentwicklung.jpg",  # oder "webdesign.jpg" falls so benannt
    "App-Entwicklung": "app-entwicklung.jpg",
    "UI/UX Design": "ui-ux-design.jpg",
    "Datenanalyse": "datenanalyse.jpg",
    "DevOps & Cloud": "devops-cloud.jpg",
    "QA & Testing": "qa-testing.jpg",
    "SEO/Content": "seo.jpg",
    "Automatisierung": "automatisierung.jpg",
    "E-Commerce & CMS": "ecommerce-cms.jpg",
    "IT & Netzwerk": "it-netzwerk.jpg",
    "Cybersecurity": "cybersecurity.jpg",
    "KI/ML & Data Science": "ki-ml-data-science.jpg",
    "Game Development": "game-development.jpg",
    "Produktmanagement": "produktmanagement.jpg",
    "Grafikdesign & Branding": "grafikdesign-branding.jpg",
    "Video & Animation": "video-animation.jpg",
    "Audio & Musik": "audio-musik.jpg",
    "Fotografie & Bildbearbeitung": "fotografie-bildbearbeitung.jpg",
    "Schreiben & Übersetzen": "schreiben-uebersetzen.jpg",
    "Digital Marketing": "digital-marketing.jpg",
    "Sales & Leadgen": "sales-leadgen.jpg",
    "Social Media Management": "social-media-management.jpg",
    "PR & Kommunikation": "pr-kommunikation.jpg",
    "Admin & Assistenz": "admin-assistenz.jpg",
    "Projektmanagement": "projektmanagement.jpg",
    "Finanzen & Buchhaltung": "finanzen-buchhaltung.jpg",
    "HR & Recruiting": "hr-recruiting.jpg",
    "Architektur & CAD": "architektur-cad.jpg",
    "E-Learning & Bildung": "e-learning-bildung.jpg",
    "Rechtsdokumente (allgemein)": "rechtsdokumente.jpg",
    "Research & Analyse": "research-analyse.jpg",
}

FEATURE_POOL = [
    # Tech
    "Responsive",
    "Dark Mode",
    "i18n",
    "CI/CD",
    "Unit Tests",
    "E2E Tests",
    "Dokumentation",
    "Monitoring",
    "Caching",
    "Auth",
    "Rollen & Rechte",
    "SEO-Basics",
    "Analytics",
    "Export (CSV/Excel)",
    "Accessibility A11y",
    "Offline-Support",
    "HLS-Streaming",
    "Image-Optimierung",
    "Rate-Limiting",
    "Security-Headers",
    "Env-Switch (Dev/Prod)",
    "Docker Support",
    # Kreativ & Content
    "Brand-Sheet",
    "Source Files",
    "Social-Templates",
    "Storyboard",
    "Untertitel/Caption",
    "Color Grading",
    "Audio Mastering",
    # Business/Marketing
    "Keyword-Recherche",
    "Redaktionsplan",
    "A/B-Test-Plan",
    "Lead-Tracking",
    "UTM-Konzept",
    "Consent-Banner",
    # Ops
    "Runbook",
    "SLA Light",
    "Backup-Plan",
    "Kostenübersicht",
    # Service
    "Express-Option",
    "2 Feedback-Runden",
    "Onboarding-Call",
    "Abschluss-Report",
]

FIRST_NAMES = [
    "Lena",
    "Jonas",
    "Mara",
    "Paul",
    "Sofia",
    "Felix",
    "Mira",
    "Lukas",
    "Ella",
    "Noah",
    "Emma",
    "Ben",
    "Lea",
    "Max",
    "Milan",
    "Mia",
    "Emil",
    "Clara",
    "Theo",
    "Nina",
    "Julius",
    "Hanna",
    "Tom",
    "Leonie",
    "Sam",
    "Ida",
    "Oskar",
    "Maja",
    "Anton",
    "Eva",
]

LAST_NAMES = [
    "Klein",
    "Meyer",
    "Schmidt",
    "Wagner",
    "Becker",
    "Hoffmann",
    "Koch",
    "Bauer",
    "Sommer",
    "Kaiser",
    "Vogel",
    "Jung",
    "Keller",
    "Schneider",
    "Fischer",
    "Weber",
    "Schulz",
    "Krüger",
    "Wolf",
    "Zimmermann",
    "Braun",
    "Hartmann",
    "Schreiber",
    "Neumann",
    "Lorenz",
    "Franke",
    "Seidel",
    "Schuster",
    "Kuhn",
    "Ott",
]

REVIEW_SENTENCES = [
    "Schnelle Lieferung und saubere Code-Basis.",
    "Sehr gute Kommunikation, klare Struktur.",
    "Top Ergebnis, jederzeit wieder.",
    "Gute Qualität, kleine Nachbesserung nötig.",
    "Abstimmung hätte schneller sein können, Ergebnis passt.",
    "Über den Erwartungen, strukturiertes Vorgehen.",
    "Tolle Ideen und professionelle Umsetzung.",
    "Termine gehalten, proaktive Updates.",
    "Preis-Leistung absolut fair.",
    "Flexibel auf Änderungen reagiert.",
    "Analyse fundiert und nachvollziehbar.",
    "Design modern, Markenfit stimmt.",
    "Technische Umsetzung stabil und performant.",
    "Storytelling gelungen und kurzweilig.",
    "Sehr gründliche Recherche, gute Quellen.",
    "Einrichtung verständlich dokumentiert.",
    "Messbare Verbesserungen nach dem Go-Live.",
    "Konstruktives Feedback, angenehme Zusammenarbeit.",
    "Wir empfehlen definitiv weiter.",
    "Gerne wieder bei zukünftigen Projekten.",
]

TIER_SCHEMES = [
    ("express", (1, 2, 3), 0.15),  # zeigt im Listing "Express 24 h"
    ("bis3", (2, 3, 5), 0.30),  # "bis zu 3 Tage"
    ("bis7", (3, 5, 7), 0.35),  # "bis zu 7 Tage"
    ("extended", (7, 14, 21), 0.20),  # längere Projekte
]
